version: '3.8'
name: nexus
services:
  nexus:
    image: sonatype/nexus3:3.53.0
    cpus: 1.0
    restart: always
    ports:
      - "8081:8081"
      - "8082:8082" 
      - "8083:8083" 
      - "5567:5567"  
    volumes:
      - nexus-storage:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms3g -Xmx3g -XX:MaxDirectMemorySize=4g -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
volumes:
  nexus-storage:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.129,rw,hard,nolock
      device: ":/export/nexus-data"
