version: '3.8'
name: sonar
services:
  sonarqube:
    image: sonarqube:10.0.0-community
    cpus: 0.500
    restart: always
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://192.168.0.126:5433/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: true
    volumes:
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_logs:/opt/sonarqube/logs 

volumes:
  sonarqube_data:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.129,rw,nolock
      device: ":/export/sonar-qa-data"
  sonarqube_extensions:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.129,rw,nolock
      device: ":/export/sonar-qa-extensions"    
  sonarqube_logs:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.0.129,rw,nolock
      device: ":/export/sonar-qa-logs"      

