version: '3.8'
name: drone-ci
services:
  drone-server:
    image: "${DRONE_SERVER_IMAGE}:${DRONE_SERVER_IMAGE_TAG}"
    container_name: ${DRONE_SERVER_CONTAINER_NAME}
    extends:
      file: compose_extra_hosts.yaml
      service: extra_hosts     
    ports:
    - "${DRONE_SERVER_PORT}:80"
    - "${DRONE_SERVER_PORT_TLS}:443"
    restart: "${RESTART_POLICY}"
    env_file:
    - .env-server
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/localtime:/etc/localtime:ro
    networks:
      drone_net:
        aliases:
          - drone-server
  drone-runner:
    image: "${DRONE_RUNNER_IMAGE}:${DRONE_RUNNER_IMAGE_TAG}"
    container_name: ${DRONE_RUNNER_CONTAINER_NAME}
    restart: "${RESTART_POLICY}"
    extends:
      file: compose_extra_hosts.yaml
      service: extra_hosts 
    depends_on:
      - drone-server
    env_file:
    - .env-runner
    ports:
    - "${DRONE_RUNNER_PORT}:3000"
    networks:
      drone_net:
        aliases:
          - drone-runner   
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /etc/localtime:/etc/localtime:ro
      
networks:
  drone_net:
    driver: bridge

     
