global:
  scrape_interval: 1m
  scrape_timeout: 10s
  evaluation_interval: 1m


rule_files:
      - "/etc/prometheus/rules/*.yaml"

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"

scrape_configs:

  - job_name: 'federate'
    scrape_interval: 15s    
  
    honor_labels: true
    metrics_path: '/federate'
  
    params:
      'match[]':
        - '{__name__=~".+"}'
        - '{job=~".+"}'
        # - '{job="prometheus"}'
        # - '{__name__=~"job:.*"}'
        # - '{job=~"*"}'
        # - '{job="node-exporter"}'
        # - '{job=~"kubernetes.*"}'
        # - '{job=~"kube.*"}'
        # - '{job=~"cloudnativepg.*"}'

    static_configs:
        - targets:
          - '192.168.0.121:30910'

  - job_name: oracledb-exporter
    static_configs:
        - targets: ["oracledb-exporter:9161"]
          labels:
            oracle_sid: "SU090077/BDESP10N"          
          
  # - job_name: postgres-exporter
  #   static_configs:
  #     - targets: ["postgres-exporter:9187"]        
          


        
